---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: uconsole-fedora-sway

description: A uConsole Atomic Fedora image with Sway WM, utilities, and more.

#base-image: ghcr.io/ublue-os/base-main
base-image: quay.io/fedora/fedora-bootc
image-version: 42-aarch64 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - negativo17

  - type: dnf
    remove:
      packages:
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
  
  - type: dnf
    repos:

    install:
      allow-erasing: true
      packages:
        - clockworkpi-audio-1.1-2.noarch.rpm

        - kernel-longterm-6.12.50-200.fc42.aarch64.rpm
        - kernel-longterm-core-6.12.50-200.fc42.aarch64.rpm
        - kernel-longterm-modules-6.12.50-200.fc42.aarch64.rpm
        - kernel-longterm-modules-core-6.12.50-200.fc42.aarch64.rpm
        - kernel-longterm-modules-extra-6.12.50-200.fc42.aarch64.rpm

        # --- Fedora IOT specific packages ---
        - fedora-release-iot
        - fedora-iot-config
        # - bcm2711-firmware
        - uboot-tools
        - uboot-images-armv8
        - arm-image-installer
        - libgpiod-utils
        - mesa-dri-drivers

        # -- Mobile packages ---
        - tlp
        - tlp-rdw

  - type: script
    scripts:
      - "rm-firmware.sh"

  - type: files
    files:
    - source: clockworkpi-cm-firmware_0.1_arm64/
      destination: /boot/firmware
    - source: uconsole-4g-util-cm4_0.2_arm64/etc/systemd/system/uconsole-4g-cm4.service
      destination: /usr/lib/systemd/system/uconsole-4g-cm4.service
    - source: uconsole-4g-util-cm4_0.2_arm64/usr/bin/uconsole-4g
      destination: /usr/bin/uconsole-4g
    - source: uconsole-4g-util-cm4_0.2_arm64/usr/local/bin/uconsole-4g-cm4
      destination: /var/usrlocal/bin/uconsole-4g-cm4

  - type: initramfs

  - type: systemd
    system:
      enabled:
        - clockworkpi-audio-patch.service
        - clockworkpi-audio-shutdown.service
        - uconsole-4g-cm4.service

  - type: signing
